# Generated by Django 5.0.1 on 2024-01-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_cursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='nome_cursos',
            new_name='nome_do_curso',
        ),
        migrations.AddField(
            model_name='cursos',
            name='aluno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='turma',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
