# Generated by Django 5.0.1 on 2024-01-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_rename_nome_cursos_cursos_nome_do_curso_cursos_aluno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='aluno',
            new_name='Carga_horária',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='turma',
            new_name='investimento',
        ),
    ]
